title: Why (为什么)
author: Liao Choon Way (廖俊伟)
email: choonway@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I dabble in the intersection between software and hardware, mathematics and physics.
  Bringing into existence that which has not existed before.
twitter_username: choonway
github_username:  choonway
rss: rss

show_excerpts: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
